services:
  nginx:
    container_name: nginx_aut-final
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8876:80"
    depends_on:
      - app

  app:
    container_name: app_aut-final
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - mysql

  mysql:
    container_name: mysql_aut-final
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: fred
      MYSQL_DATABASE: automationFinal_db
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql
